### ISSUE TITLE
When will the checkpoint be uploaded?

### ISSUE THREAD

**Issue by JanRiebe** [KwaiVGI/SynCamMaster#1]
Great work and thank you for uploading your code!
I think understanding your work in detail might help me with my master thesis. Therefore I'd like to try it out my self.
Do you have an estimate when you will be able to upload the checkpoint?
Thank you!

**Comment by JianhongBai** [comment]
Thank you for your interest in our work! The model used in our paper is an internal T2V model that cannot be released due to company policy restrictions. We are in the process of migrating our method to CogVideoX and retraining it. We plan to upload the checkpoint within a month. In the meantime, you can explore the details of our method at https://github.com/KwaiVGI/SynCamMaster?tab=readme-ov-file#3-code-snapshot.

**Comment by JanRiebe** [comment]
Thank you for the quick response!
